/**
 * Storage Service
 * Persists analysis runs to localStorage.
 * Mirrors World Monitor's circuit-breaker persistent cache concept.
 */
import type { AnalysisRun, SharedMemory, WorkspaceConfig } from '@/types';

const STORAGE_KEY = 'insight-runs';
const MAX_RUNS = 10;

function getAll(): AnalysisRun[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return [];
    return JSON.parse(raw) as AnalysisRun[];
  } catch {
    return [];
  }
}

function saveAll(runs: AnalysisRun[]): void {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(runs));
  } catch {
    console.warn('[Storage] localStorage write failed');
  }
}

export function saveAnalysisRun(config: WorkspaceConfig, memory: SharedMemory): AnalysisRun {
  const runs = getAll();
  const run: AnalysisRun = {
    id: `run-${Date.now()}`,
    workspaceConfig: config,
    memory,
    createdAt: Date.now(),
    label: `${config.companyName || 'Analysis'} — ${new Date().toLocaleDateString()}`,
  };

  const updated = [run, ...runs].slice(0, MAX_RUNS);
  saveAll(updated);
  return run;
}

export function loadAnalysisRuns(): AnalysisRun[] {
  return getAll();
}

export function deleteAnalysisRun(id: string): void {
  const runs = getAll().filter(r => r.id !== id);
  saveAll(runs);
}

export function exportJson(memory: SharedMemory, config: WorkspaceConfig): void {
  const blob = new Blob([JSON.stringify({ config, memory }, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `insight-report-${Date.now()}.json`;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportText(memory: SharedMemory, config: WorkspaceConfig): void {
  const summary = memory.executiveSummary;
  const lines = [
    '═══════════════════════════════════════════════════════',
    '         INSIGHT — R&D INTELLIGENCE REPORT',
    '═══════════════════════════════════════════════════════',
    '',
    `Company: ${config.companyName}`,
    `Industry: ${config.industry}`,
    `Target Market: ${config.targetMarket}`,
    `Generated: ${new Date().toLocaleString()}`,
    `Posts Analyzed: ${memory.rawPosts.length}`,
    `Signals Found: ${memory.signals.length}`,
    '',
    '─── EXECUTIVE SUMMARY ─────────────────────────────────',
    summary?.headline ?? 'N/A',
    '',
    `Top Opportunity: ${summary?.topOpportunity ?? 'N/A'}`,
    `Top Risk: ${summary?.topRisk ?? 'N/A'}`,
    '',
    '─── STRATEGIC INSIGHTS ────────────────────────────────',
    ...(summary?.insights ?? []).flatMap(ins => [
      '',
      `▶ ${ins.title}`,
      ins.body,
    ]),
    '',
    '─── SIGNAL DETAILS ────────────────────────────────────',
    ...memory.signals.slice(0, 10).flatMap(sig => [
      '',
      `[${sig.severity.toUpperCase()}] ${sig.label} — Score: ${sig.score}/100`,
      `  Volume: ${sig.volume} posts | Negativity: ${sig.negativity}% | Growth: ${sig.growthRate}%`,
      `  ${sig.description}`,
      ...(sig.risks.length > 0 ? [`  Risks: ${sig.risks[0]}`] : []),
      ...(sig.opportunities.length > 0 ? [`  Opportunity: ${sig.opportunities[0]}`] : []),
    ]),
    '',
    '═══════════════════════════════════════════════════════',
    '  Generated by Insight — Multi-Agent R&D Intelligence',
    '═══════════════════════════════════════════════════════',
  ];

  const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `insight-report-${Date.now()}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}
